import {defineConfig} from 'oxlint'

const MAX_LINES_PER_FILE = 600

export default defineConfig({
  env: {
    builtin: true,
    node: true,
  },
  ignorePatterns: ['dist/*', 'coverage/*', '.agents/**'],
  jsPlugins: [
    'oxlint-plugin-eslint',
    {
      name: 'sort-export-all',
      specifier: 'eslint-plugin-sort-export-all',
    },
  ],
  overrides: [
    {
      files: ['**/*.spec.{ts,tsx,js,jsx}', '**/*.test.{ts,tsx,js,jsx}'],
      rules: {
        '@typescript-eslint/no-unused-vars': 'off',
        '@typescript-eslint/no-var-requires': 'off',
        'eslint-js/camelcase': 'off',
        'eslint-js/no-magic-numbers': 'off',
        'eslint-js/no-mixed-operators': 'off',
        'eslint-js/prefer-named-capture-group': 'off',
        'eslint-js/require-unicode-regexp': 'off',
        'id-length': 'off',
        'max-classes-per-file': 'off',
        'max-lines': 'off',
        'max-lines-per-function': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        'no-empty-function': 'off',
        'no-magic-numbers': 'off',
        'no-unassigned-vars': 'off',
        'no-unsafe-optional-chaining': 'off',
        'no-void': 'off',
        'prefer-destructuring': 'off',
        'unicorn/consistent-function-scoping': 'off',
        'unicorn/no-useless-undefined': 'off',
      },
    },
    {
      files: ['**/*.js'],
      rules: {
        '@typescript-eslint/no-var-requires': 'off',
        'unicorn/prefer-module': 'off',
      },
    },
  ],
  plugins: ['typescript', 'unicorn', 'oxc', 'import', 'promise', 'node'],
  rules: {
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
      },
    ],
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        args: 'after-used',
        argsIgnorePattern: '^_+$',
        ignoreRestSiblings: true,
      },
    ],
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'arrow-body-style': 'off',
    'block-scoped-var': 'error',
    complexity: 'error',
    'consistent-return': 'off',
    curly: 'error',
    'default-case': 'off',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    eqeqeq: ['error', 'smart'],
    'eslint-js/array-bracket-newline': ['error', 'consistent'],
    'eslint-js/array-bracket-spacing': ['error', 'never'],
    'eslint-js/arrow-parens': ['error', 'always'],
    'eslint-js/arrow-spacing': ['error', {after: true, before: true}],
    'eslint-js/block-spacing': ['error', 'never'],
    'eslint-js/brace-style': ['error', '1tbs', {allowSingleLine: true}],
    'eslint-js/camelcase': ['error', {ignoreGlobals: true, ignoreImports: true, properties: 'always'}],
    'eslint-js/comma-dangle': ['error', 'always-multiline'],
    'eslint-js/comma-spacing': ['error', {after: true, before: false}],
    'eslint-js/computed-property-spacing': ['error', 'never'],
    'eslint-js/eol-last': 'error',
    'eslint-js/func-call-spacing': ['error', 'never'],
    'eslint-js/function-call-argument-newline': ['error', 'consistent'],
    'eslint-js/function-paren-newline': 'off',
    'eslint-js/generator-star-spacing': ['error', {after: false, before: true}],
    'eslint-js/indent': 'off',
    'eslint-js/jsx-quotes': ['error', 'prefer-double'],
    'eslint-js/key-spacing': ['error', {afterColon: true, beforeColon: false, mode: 'strict'}],
    'eslint-js/keyword-spacing': ['error', {after: true, before: true}],
    'eslint-js/line-comment-position': ['warn', {position: 'above'}],
    'eslint-js/max-len': ['error', {code: 120, ignoreComments: true, ignoreTrailingComments: true, ignoreUrls: true}],
    'eslint-js/max-statements-per-line': ['error', {max: 2}],
    'eslint-js/no-confusing-arrow': 'warn',
    'eslint-js/no-extra-parens': ['error', 'functions'],
    'eslint-js/no-floating-decimal': 'error',
    'eslint-js/no-implicit-globals': 'off',
    'eslint-js/no-magic-numbers': 'off',
    'eslint-js/no-mixed-spaces-and-tabs': 'error',
    'eslint-js/no-multi-spaces': 'error',
    'eslint-js/no-multiple-empty-lines': ['error', {max: 1, maxEOF: 1}],
    'eslint-js/no-tabs': 'error',
    'eslint-js/no-trailing-spaces': 'error',
    'eslint-js/no-whitespace-before-property': 'error',
    'eslint-js/object-curly-spacing': ['error', 'never'],
    'eslint-js/one-var': ['error', 'never'],
    'eslint-js/prefer-arrow-callback': 'off',
    'eslint-js/prefer-named-capture-group': 'error',
    'eslint-js/quote-props': ['error', 'as-needed'],
    'eslint-js/require-unicode-regexp': 'error',
    'eslint-js/rest-spread-spacing': 'error',
    'eslint-js/semi': ['error', 'never'],
    'eslint-js/space-before-blocks': ['error', {classes: 'always', functions: 'always', keywords: 'always'}],
    'eslint-js/space-before-function-paren': ['error', {anonymous: 'always', asyncArrow: 'always', named: 'never'}],
    'eslint-js/space-in-parens': ['error', 'never'],
    'eslint-js/space-infix-ops': 'error',
    'eslint-js/space-unary-ops': 'error',
    'eslint-js/template-curly-spacing': ['error', 'never'],
    'func-names': ['error', 'as-needed'],
    'func-style': ['error', 'declaration', {allowArrowFunctions: true}],
    'id-length': ['error', {exceptionPatterns: ['^[A-Z]$'], exceptions: ['_', 'x', 'y', 'z', 'p', 'm']}],
    'import/named': 'off',
    'import/no-absolute-path': 'off',
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        cjs: 'never',
        css: 'always',
        js: 'never',
        json: 'always',
        jsx: 'never',
        mjs: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'max-classes-per-file': 'error',
    'max-depth': ['error', {max: 4}],
    'max-lines': ['error', MAX_LINES_PER_FILE],
    'max-lines-per-function': ['error', {max: 150, skipBlankLines: true, skipComments: true}],
    'max-nested-callbacks': ['error', {max: 3}],
    'max-params': ['error', {max: 4}],
    'max-statements': ['error', {max: 40}],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-await-in-loop': 'error',
    'no-bitwise': 'error',
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-duplicate-imports': 'warn',
    'no-empty-function': 'error',
    'no-eval': 'error',
    'no-extra-bind': 'error',
    'no-magic-numbers': ['error', {ignore: [1, -1, 0, 2], ignoreArrayIndexes: true}],
    'no-param-reassign': 'error',
    'no-plusplus': 'error',
    'no-redeclare': 'off',
    'no-shadow': 'off',
    'no-undef': 'off',
    'no-undefined': 'off',
    'no-unused-expressions': 'off',
    'no-unused-vars': 'off',
    'no-use-before-define': 'off',
    'no-var': 'error',
    'no-void': 'error',
    'operator-assignment': ['warn', 'always'],
    'prefer-const': 'error',
    'prefer-destructuring': 'warn',
    'prefer-object-spread': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'warn',
    radix: 'error',
    'sort-export-all/sort-export-all': 'warn',
    'sort-imports': ['warn', {ignoreCase: true, ignoreDeclarationSort: true}],
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/filename-case': ['warn', {cases: {kebabCase: true, pascalCase: true}}],
    'unicorn/new-for-builtins': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-module': 'off',
    'unicorn/prefer-node-protocol': 'off',
    'unicorn/prefer-ternary': 'off',
    yoda: 'error',
  },
  settings: {},
})
